eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/
    health-check-url: http://${spring.cloud.client.ipAddress}:${server.port}/health
    home-page-url: http://${spring.cloud.client.ipAddress}:${server.port}

zuul:
  routes:
    eureka-client:
      path: /endpoint1/**
      serviseId: eureka-client

info:
  description: router
  version: 1.0

server:
  port: 8080